-- Create data warehouse
CREATE WAREHOUSE IF NOT EXISTS analytics_wh
  WAREHOUSE_SIZE = SMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Create compute warehouse for heavy operations
CREATE WAREHOUSE IF NOT EXISTS etl_wh
  WAREHOUSE_SIZE = MEDIUM
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Create reporting warehouse
CREATE WAREHOUSE IF NOT EXISTS reporting_wh
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
